#!/bin/bash

cd ${BEETEMPSDIR}
git checkout public

USTAMP=`date +%s`
USTAMP=$(( USTAMP*1000 ))

# temps
# 24 hour image
START=$(( USTAMP-86400000 ))
curl -H "Authorization: Bearer ${BEETOKEN}"  \
"http://localhost:3000/render/d-solo/wVh0pof7z/bees?orgId=2&refresh=1m&from=${START}&to=${USTAMP}&panelId=4&width=1600&height=600&tz=America%2FVancouver" > Beehive_24.png

# 1 week
START=$(( USTAMP-604800000 ))
curl -H "Authorization: Bearer ${BEETOKEN}"  \
"http://localhost:3000/render/d-solo/wVh0pof7z/bees?orgId=2&refresh=1m&from=${START}&to=${USTAMP}&panelId=4&width=1600&height=600&tz=America%2FVancouver" > Beehive_7d.png

# 1 month
START=$(( USTAMP-2419200000 ))
curl -H "Authorization: Bearer ${BEETOKEN}"  \
"http://localhost:3000/render/d-solo/wVh0pof7z/bees?orgId=2&refresh=1m&from=${START}&to=${USTAMP}&panelId=4&width=1600&height=600&tz=America%2FVancouver" > Beehive_4w.png

# humid
# 24 hour image
START=$(( USTAMP-86400000 ))
curl -H "Authorization: Bearer ${BEETOKEN}"  \
"http://localhost:3000/render/d-solo/wVh0pof7z/bees?orgId=2&refresh=1m&from=${START}&to=${USTAMP}&panelId=6&width=1600&height=600&tz=America%2FVancouver" > Beehive_H_24.png

# 1 week
START=$(( USTAMP-604800000 ))
curl -H "Authorization: Bearer ${BEETOKEN}"  \
"http://localhost:3000/render/d-solo/wVh0pof7z/bees?orgId=2&refresh=1m&from=${START}&to=${USTAMP}&panelId=6&width=1600&height=600&tz=America%2FVancouver" > Beehive_H_7d.png

# 1 month
START=$(( USTAMP-2419200000 ))
curl -H "Authorization: Bearer ${BEETOKEN}"  \
"http://localhost:3000/render/d-solo/wVh0pof7z/bees?orgId=2&refresh=1m&from=${START}&to=${USTAMP}&panelId=6&width=1600&height=600&tz=America%2FVancouver" > Beehive_H_4w.png

# hive

# humid
# 24 hour image
START=$(( USTAMP-86400000 ))
curl -H "Authorization: Bearer ${BEETOKEN}"  \
"http://localhost:3000/render/d-solo/wVh0pof7z/bees?orgId=2&refresh=1m&from=${START}&to=${USTAMP}&panelId=2&width=1600&height=600&tz=America%2FVancouver" > Beehive_I_24.png

# 1 week
START=$(( USTAMP-604800000 ))
curl -H "Authorization: Bearer ${BEETOKEN}"  \
"http://localhost:3000/render/d-solo/wVh0pof7z/bees?orgId=2&refresh=1m&from=${START}&to=${USTAMP}&panelId=2&width=1600&height=600&tz=America%2FVancouver" > Beehive_I_7d.png

# 1 month
START=$(( USTAMP-2419200000 ))
curl -H "Authorization: Bearer ${BEETOKEN}"  \
"http://localhost:3000/render/d-solo/wVh0pof7z/bees?orgId=2&refresh=1m&from=${START}&to=${USTAMP}&panelId=2&width=1600&height=600&tz=America%2FVancouver" > Beehive_I_4w.png

thistime=`date`
git commit -a -m "Adding data for ${thistime}"
